project:
  artifactId: finance-web
  name: finance-web
  description: finance-web

# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  name: finance
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false
  require_ssl: false
  ignored: 
    - /lib/**
    - /css/**
    - /static/**
    - /font-custom/**
    - /img/**
    - /500
    - /404
    
spring:
  thymeleaf:
    cache: false
    mode: html
    




    
    
